AllCops:
    NewCops: disable
    TargetRubyVersion: 2.7

Bundler/OrderedGems:
    Enabled: false

Style/Alias:
    Enabled: false

Style/FrozenStringLiteralComment:
    Enabled: false

Style/NumericLiterals:
    Enabled: false

Style/TrailingCommaInArrayLiteral:
    Enabled: false

Style/TrailingCommaInHashLiteral:
    Enabled: false

Style/TrailingCommaInArguments:
    Enabled: false

Style/Documentation:
    Enabled: false

Style/DoubleNegation:
    Enabled: false

Style/WordArray:
    Enabled: false

Style/ClassAndModuleChildren:
    Enabled: false

Layout/EndOfLine:
   EnforcedStyle: lf

Layout/TrailingEmptyLines:
    Enabled: true

Layout/LineLength:
    Max: 120
    Enabled: false
    IgnoredPatterns:

Metrics/ClassLength:
    Enabled: false

Metrics/MethodLength:
    Max: 50

Metrics/AbcSize:
    Max: 25 # TODO: Restore to '20'

Metrics/BlockLength:
    Max: 40

Naming/VariableNumber:
    Enabled: false

Lint/MissingSuper:
    Enabled: false

Style/OptionalBooleanParameter:
    Enabled: false