# frozen_string_literal: true

class ServiceRequirements < SitePrism::Page
  sections :service_table, 'tr.govuk-table__row' do
    element :name, 'th'
    elements :volume, 'td:nth-child(3)'
  end

  element :answer_question, 'td > a'
  elements :change_link, 'td > a'
  element :select_all, '#box-all'

  element :building_standard_text, 'tr:nth-child(1)'

  elements :volume, 'tr.govuk-table__row > td:nth-child(3)'

  element :bms, '[value="C.11"]'
  element :env_cleaning, '[value="C.3"]'
  element :fire_detection_maintenance, '[value="C.4"]'
  element :high_voltage, '[value="C.13"]'
  element :internal_external_building, '[value="C.7"]'
  element :lifts_hoists, '[value="C.5"]'
  element :mech_elec, '[value="C.1"]'
  element :security_access, '[value="C.6"]'
  element :standby_power, '[value="C.12"]'
  element :ventilation, '[value="C.2"]'
  element :asbestos, '[value="E.1"]'
  element :compliance_plans, '[value="E.5"]'
  element :condition_survey, '[value="E.6"]'
  element :electrical_testing, '[value="E.7"]'
  element :fire_risk, '[value="E.8"]'
  element :portable_appliance, '[value="E.4"]'
  element :statutory_inspections, '[value="E.3"]'
  element :water_hygiene, '[value="E.2"]'
  element :cleaning_external, '[value="G.5"]'
  element :cleaning_integral, '[value="G.2"]'
  element :deep_periodic_clean, '[value="G.4"]'
  element :mobile_cleaning, '[value="G.3"]'
  element :pest_control, '[value="G.15"]'
  element :routine_cleaning, '[value="G.1"]'
  element :external_window_cleaning, '[value="G.7"]'
  element :internal_window_cleaning, '[value="G.6"]'
  element :handyman_services, '[value="H.4"]'
  element :move_space_manage, '[value="H.5"]'
  element :car_park, '[value="I.3"]'
  element :reception_services, '[value="I.1"]'
  element :taxi_booking, '[value="I.2"]'
  element :voice_announce, '[value="I.4"]'
  element :cctv, '[value="J.2"]'
  element :control_access, '[value="J.3"]'
  element :emergency_response, '[value="J.4"]'
  element :managements_visitor, '[value="J.6"]'
  element :manned_guarding, '[value="J.1"]'
  element :patrols_fixed, '[value="J.5"]'
  element :classified_waste, '[value="K.1"]'
  element :feminine_hygiene, '[value="K.7"]'
  element :general_waste, '[value="K.2"]'
  element :recycled_waste, '[value="K.3"]'
  element :cafm, '[value="M.1"]'
  element :helpdesk, '[value="N.1"]'
  element :management_billable, '[value="O.1"]'
  element :select_all, '[name="box-all"]'

  section :aberdeen_services, '#aberdeen-services' do
    element :bms, '[value="C.11"]'
    element :env_cleaning, '[value="C.3"]'
    element :fire_detection_maintenance, '[value="C.4"]'
    element :high_voltage, '[value="C.13"]'
    element :internal_external_building, '[value="C.7"]'
    element :lifts_hoists, '[value="C.5"]'
    element :mech_elec, '[value="C.1"]'
    element :security_access, '[value="C.6"]'
    element :standby_power, '[value="C.12"]'
    element :ventilation, '[value="C.2"]'
    element :asbestos, '[value="E.1"]'
    element :compliance_plans, '[value="E.5"]'
    element :condition_survey, '[value="E.6"]'
    element :electrical_testing, '[value="E.7"]'
    element :fire_risk, '[value="E.8"]'
    element :portable_appliance, '[value="E.4"]'
    element :statutory_inspections, '[value="E.3"]'
    element :water_hygiene, '[value="E.2"]'
    element :cleaning_external, '[value="G.5"]'
    element :cleaning_integral, '[value="G.2"]'
    element :deep_periodic_clean, '[value="G.4"]'
    element :mobile_cleaning, '[value="G.3"]'
    element :pest_control, '[value="G.15"]'
    element :routine_cleaning, '[value="G.1"]'
    element :external_window_cleaning, '[value="G.7"]'
    element :internal_window_cleaning, '[value="G.6"]'
    element :handyman_services, '[value="H.4"]'
    element :move_space_manage, '[value="H.5"]'
    element :car_park, '[value="I.3"]'
    element :reception_services, '[value="I.1"]'
    element :taxi_booking, '[value="I.2"]'
    element :voice_announce, '[value="I.4"]'
    element :cctv, '[value="J.2"]'
    element :control_access, '[value="J.3"]'
    element :emergency_response, '[value="J.4"]'
    element :managements_visitor, '[value="J.6"]'
    element :manned_guarding, '[value="J.1"]'
    element :patrols_fixed, '[value="J.5"]'
    element :classified_waste, '[value="K.1"]'
    element :feminine_hygiene, '[value="K.7"]'
    element :general_waste, '[value="K.2"]'
    element :recycled_waste, '[value="K.3"]'
    element :cafm, '[value="M.1"]'
    element :helpdesk, '[value="N.1"]'
    element :management_billable, '[value="O.1"]'
    element :select_all, '[name="box-all"]'
  end

  section :belfast_building_services, '#belfast_building-services' do
    element :bms, '[value="C.11"]'
    element :env_cleaning, '[value="C.3"]'
    element :fire_detection_maintenance, '[value="C.4"]'
    element :high_voltage, '[value="C.13"]'
    element :internal_external_building, '[value="C.7"]'
    element :lifts_hoists, '[value="C.5"]'
    element :mech_elec, '[value="C.1"]'
    element :security_access, '[value="C.6"]'
    element :standby_power, '[value="C.12"]'
    element :ventilation, '[value="C.2"]'
    element :asbestos, '[value="E.1"]'
    element :compliance_plans, '[value="E.5"]'
    element :condition_survey, '[value="E.6"]'
    element :electrical_testing, '[value="E.7"]'
    element :fire_risk, '[value="E.8"]'
    element :portable_appliance, '[value="E.4"]'
    element :statutory_inspections, '[value="E.3"]'
    element :water_hygiene, '[value="E.2"]'
    element :cleaning_external, '[value="G.5"]'
    element :cleaning_integral, '[value="G.2"]'
    element :deep_periodic_clean, '[value="G.4"]'
    element :mobile_cleaning, '[value="G.3"]'
    element :pest_control, '[value="G.15"]'
    element :routine_cleaning, '[value="G.1"]'
    element :external_window_cleaning, '[value="G.7"]'
    element :internal_window_cleaning, '[value="G.6"]'
    element :handyman_services, '[value="H.4"]'
    element :move_space_manage, '[value="H.5"]'
    element :car_park, '[value="I.3"]'
    element :reception_services, '[value="I.1"]'
    element :taxi_booking, '[value="I.2"]'
    element :voice_announce, '[value="I.4"]'
    element :cctv, '[value="J.2"]'
    element :control_access, '[value="J.3"]'
    element :emergency_response, '[value="J.4"]'
    element :managements_visitor, '[value="J.6"]'
    element :manned_guarding, '[value="J.1"]'
    element :patrols_fixed, '[value="J.5"]'
    element :classified_waste, '[value="K.1"]'
    element :feminine_hygiene, '[value="K.7"]'
    element :general_waste, '[value="K.2"]'
    element :recycled_waste, '[value="K.3"]'
    element :cafm, '[value="M.1"]'
    element :helpdesk, '[value="N.1"]'
    element :management_billable, '[value="O.1"]'
    element :select_all, '[name="box-all"]'
  end

  section :birmingham_services, '#birmingham-services' do
    element :bms, '[value="C.11"]'
    element :env_cleaning, '[value="C.3"]'
    element :fire_detection_maintenance, '[value="C.4"]'
    element :high_voltage, '[value="C.13"]'
    element :internal_external_building, '[value="C.7"]'
    element :lifts_hoists, '[value="C.5"]'
    element :mech_elec, '[value="C.1"]'
    element :security_access, '[value="C.6"]'
    element :standby_power, '[value="C.12"]'
    element :ventilation, '[value="C.2"]'
    element :asbestos, '[value="E.1"]'
    element :compliance_plans, '[value="E.5"]'
    element :condition_survey, '[value="E.6"]'
    element :electrical_testing, '[value="E.7"]'
    element :fire_risk, '[value="E.8"]'
    element :portable_appliance, '[value="E.4"]'
    element :statutory_inspections, '[value="E.3"]'
    element :water_hygiene, '[value="E.2"]'
    element :cleaning_external, '[value="G.5"]'
    element :cleaning_integral, '[value="G.2"]'
    element :deep_periodic_clean, '[value="G.4"]'
    element :mobile_cleaning, '[value="G.3"]'
    element :pest_control, '[value="G.15"]'
    element :routine_cleaning, '[value="G.1"]'
    element :external_window_cleaning, '[value="G.7"]'
    element :internal_window_cleaning, '[value="G.6"]'
    element :handyman_services, '[value="H.4"]'
    element :move_space_manage, '[value="H.5"]'
    element :car_park, '[value="I.3"]'
    element :reception_services, '[value="I.1"]'
    element :taxi_booking, '[value="I.2"]'
    element :voice_announce, '[value="I.4"]'
    element :cctv, '[value="J.2"]'
    element :control_access, '[value="J.3"]'
    element :emergency_response, '[value="J.4"]'
    element :managements_visitor, '[value="J.6"]'
    element :manned_guarding, '[value="J.1"]'
    element :patrols_fixed, '[value="J.5"]'
    element :classified_waste, '[value="K.1"]'
    element :feminine_hygiene, '[value="K.7"]'
    element :general_waste, '[value="K.2"]'
    element :recycled_waste, '[value="K.3"]'
    element :cafm, '[value="M.1"]'
    element :helpdesk, '[value="N.1"]'
    element :management_billable, '[value="O.1"]'
    element :select_all, '[name="box-all"]'
  end

  section :westminster_building_services, '#westminster_building-services' do
    element :bms, '[value="C.11"]'
    element :env_cleaning, '[value="C.3"]'
    element :fire_detection_maintenance, '[value="C.4"]'
    element :high_voltage, '[value="C.13"]'
    element :internal_external_building, '[value="C.7"]'
    element :lifts_hoists, '[value="C.5"]'
    element :mech_elec, '[value="C.1"]'
    element :security_access, '[value="C.6"]'
    element :standby_power, '[value="C.12"]'
    element :ventilation, '[value="C.2"]'
    element :asbestos, '[value="E.1"]'
    element :compliance_plans, '[value="E.5"]'
    element :condition_survey, '[value="E.6"]'
    element :electrical_testing, '[value="E.7"]'
    element :fire_risk, '[value="E.8"]'
    element :portable_appliance, '[value="E.4"]'
    element :statutory_inspections, '[value="E.3"]'
    element :water_hygiene, '[value="E.2"]'
    element :cleaning_external, '[value="G.5"]'
    element :cleaning_integral, '[value="G.2"]'
    element :deep_periodic_clean, '[value="G.4"]'
    element :mobile_cleaning, '[value="G.3"]'
    element :pest_control, '[value="G.15"]'
    element :routine_cleaning, '[value="G.1"]'
    element :external_window_cleaning, '[value="G.7"]'
    element :internal_window_cleaning, '[value="G.6"]'
    element :handyman_services, '[value="H.4"]'
    element :move_space_manage, '[value="H.5"]'
    element :car_park, '[value="I.3"]'
    element :reception_services, '[value="I.1"]'
    element :taxi_booking, '[value="I.2"]'
    element :voice_announce, '[value="I.4"]'
    element :cctv, '[value="J.2"]'
    element :control_access, '[value="J.3"]'
    element :emergency_response, '[value="J.4"]'
    element :managements_visitor, '[value="J.6"]'
    element :manned_guarding, '[value="J.1"]'
    element :patrols_fixed, '[value="J.5"]'
    element :classified_waste, '[value="K.1"]'
    element :feminine_hygiene, '[value="K.7"]'
    element :general_waste, '[value="K.2"]'
    element :recycled_waste, '[value="K.3"]'
    element :cafm, '[value="M.1"]'
    element :helpdesk, '[value="N.1"]'
    element :management_billable, '[value="O.1"]'
    element :select_all, '[name="box-all"]'
  end

  # element :portable_appliance_volume, '#facilities_management_procurement_building_procurement_building_services_attributes_7_no_of_appliances_for_testing'
  # element :mobile_cleaning_volume, '#facilities_management_procurement_building_procurement_building_services_attributes_9_no_of_building_occupants'
  # element :cleaning_external_area, ''

  element :portable_appliance_volume,
          '[name="facilities_management_procurement_building_service[no_of_appliances_for_testing]"]'
  element :mobile_cleaning_volume,
          '[name="facilities_management_procurement_building_service[no_of_building_occupants]"]'
  element :cleaning_external_area, '.cleaning_of_external_areas-input'
  element :routine_cleaning_volume,
          '[name="facilities_management_procurement_building_service[no_of_building_occupants]"]'
  element :general_waste_volume,
          '[name="facilities_management_procurement_building_service[tones_to_be_collected_and_removed]"]'
  element :recycled_waste_volume,
          '[name="facilities_management_procurement_building_service[tones_to_be_collected_and_removed]"]'
  element :classified_waste_volume,
          '[name="facilities_management_procurement_building_service[no_of_consoles_to_be_serviced]"]'
  element :feminine_hygiene_volume,
          '[name="facilities_management_procurement_building_service[no_of_units_to_be_serviced]"]'
  element :hazardous_waste,
          '[name="facilities_management_procurement_building_service[tones_to_be_collected_and_removed]"]'
  element :clinical_waste,
          '[name="facilities_management_procurement_building_service[tones_to_be_collected_and_removed]"]'
  element :hazardous_waste,
          '[name="facilities_management_procurement_building_service[tones_to_be_collected_and_removed]"]'
  element :medical_waste,
          '[name="facilities_management_procurement_building_service[tones_to_be_collected_and_removed]"]'

  element :number_of_personel, '#facilities_management_procurement_building_service_service_hours_personnel'

  element :number_of_hours, '#facilities_management_procurement_building_service_service_hours'
  element :service_hours_requirement, '#facilities_management_procurement_building_service_detail_of_requirement'
  sections :lift_floor, '.lift-row' do
    element :data, 'input'
  end

  element :mech_service_volume, '[id="C.1-gia-volume"]'
  element :cleaning_external_service_volume, '[id="G.5-external_area-volume"]'

  element :number_of_buildings, '#number-of-buildings'
end
